druid-datasource:
  url: jdbc:mysql://127.0.0.1:3306/tianmigangwan?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456



mybatis:
  type-aliases-package: com.tianmigangwan.pojo
  mapper-locations: classpath:com/tianmigangwan/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



spring:
  mail:
    username: 898469219@qq.com
    password: ofmggvcvanbmbcdj
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true